# Generated by Django 2.1.4 on 2021-06-21 12:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('excel_data', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('status', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_sheet_data',
            },
        ),
    ]
